### ISSUE TITLE
The timer goes slow.

### ISSUE THREAD

**Issue by duqian42707** [zengtianyu1215/SimpleClock#2]
**Describe the bug**
*The timer goes slow.*

**To Reproduce**
*1、Set a time, and start the timer. (I set 3 hours and 34 minues.)*
*2、Go to work for a few moment.*
*3、back to the timer and see.* 

**Expected behavior**
*A clear and concise description of what you expected to happen*

**Screenshots (Optional)**
<img width="529" alt="1" src="https://user-images.githubusercontent.com/13977907/48401554-6f9b6180-e764-11e8-9a99-7fcaebb33e27.png">
<img width="525" alt="2" src="https://user-images.githubusercontent.com/13977907/48401572-775b0600-e764-11e8-875d-b3c588014ca7.png">

**Desktop (please complete the following information):**
 - Mac OS X  Version: *1.8*

**Additional context**
*倒计时，表走得不准。*

**Comment by zengtianyu1215** [comment]
I'll fix this bug in a few days. But one more question: how often will you meet this issue? 
Thanks!

**Comment by zengtianyu1215** [comment]
I've found the reason why the timer goes slow. The reason is that on Mac OS X platform, activating App Nap is the default option for any application. If you deactivate the App Nap in you Mac, it will work properly. I'll fix this bug in codes. Thanks.
