### ISSUE TITLE
无法应用和保存设置。Can' t apply and save preferences in app.

### ISSUE THREAD

**Issue by danielmzy** [zengtianyu1215/SimpleClock#3]
设置不了，把设置里的都选上点应用不生效，所以无法保存设置，已清理缓存和重装应用，无效。应用很不错，希望改进。

Can't set preferences, choose all the settings but it didn't work, so it cannot save the preferences, already cleaned the data from the app and reinstall the app, not working, too. Very excellent app, hope to fix these bugs.

**Comment by zengtianyu1215** [comment]
SimpleClock的设置还在开发中，目前软件的Preference保存的是主时钟窗口退出时的状态。
 
如果您的Mac有touch bar，软件会记录touch bar上面的设置，如果没有会记录右键菜单的设置。如果还不熟悉如何使用，你可以去阅读历代版本的changelog。
 
设置界面在未来主要是用于切换字体和大小，上面的选项还不够完善，仍需要进一步开发，望谅解。

**Comment by danielmzy** [comment]
谢谢解答，好应用，支持。
